name: Vercel Production (Service) Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - service
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (docs)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd=service

      - name: Build Project Artifacts (docs)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=service

      - name: Deploy Project Artifacts to Vercel (docs)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=service
