name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - '*/docs/*'
      - '*/service/*'
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Determine the deployment directory based on the branch
      - name: Set Deployment Directory
        id: set-dir
        run: |
          if [[ $GITHUB_REF == ' refs/heads/preview/docs/*' ]]; then
            echo "::set-output name=dir::docs"
          elif [[ $GITHUB_REF == ' refs/heads/preview/service/*' ]]; then
            echo "::set-output name=dir::service"
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --cwd=${{ steps.set-dir.outputs.dir }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --cwd=${{ steps.set-dir.outputs.dir }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd=${{ steps.set-dir.outputs.dir }}
